// SwooshCLI/CompletionCommands.swift — Shell completion install — 0.9P
//
// `swoosh completions <shell>` prints a shell completion script;
// `--install` writes it to a per-user location and prints the single
// line needed to activate it. The script is generated by
// swift-argument-parser from the live command tree, so it always covers
// every current subcommand, flag, and option and never goes stale.

import ArgumentParser
import Foundation

struct CompletionsCommand: AsyncParsableCommand {
    static let configuration = CommandConfiguration(
        commandName: "completions",
        abstract: "Generate or install a shell completion script.",
        discussion: """
        Examples:
          swoosh completions zsh               Print the zsh completion script.
          swoosh completions zsh --install     Install it for the current user.
          swoosh completions bash --install    Same, for bash.
          swoosh completions fish --install    Same, for fish.

        Completion covers every subcommand, flag, and option — it is
        generated from the live command tree, so it never drifts.
        """
    )

    @Argument(help: "Target shell: zsh, bash, or fish.")
    var shell: String

    @Flag(name: .long, help: "Write the script to a per-user location and print activation steps.")
    var install = false

    func run() async throws {
        guard let completionShell = CompletionShell(rawValue: shell.lowercased()) else {
            throw ValidationError("Unsupported shell '\(shell)'. Choose zsh, bash, or fish.")
        }
        let script = SwooshCommand.completionScript(for: completionShell)
        guard install else {
            print(script)
            return
        }
        let destination = try writeScript(script, shell: completionShell)
        printActivation(shell: completionShell, path: destination)
    }

    /// Write the completion script to its conventional per-user path.
    private func writeScript(_ script: String, shell: CompletionShell) throws -> URL {
        let home = FileManager.default.homeDirectoryForCurrentUser
        let directory: URL
        let filename: String
        switch shell.rawValue {
        case "fish":
            // fish auto-discovers completions from this directory.
            directory = home.appendingPathComponent(".config/fish/completions", isDirectory: true)
            filename = "swoosh.fish"
        case "bash":
            directory = home.appendingPathComponent(".swoosh/completions", isDirectory: true)
            filename = "swoosh.bash"
        default: // zsh — completion files are conventionally named `_<command>`.
            directory = home.appendingPathComponent(".swoosh/completions", isDirectory: true)
            filename = "_swoosh"
        }
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        let url = directory.appendingPathComponent(filename)
        try script.write(to: url, atomically: true, encoding: .utf8)
        return url
    }

    private func printActivation(shell: CompletionShell, path: URL) {
        print("Installed \(shell.rawValue) completion → \(path.path)")
        switch shell.rawValue {
        case "fish":
            print("fish loads it automatically — open a new shell to use it.")
        case "bash":
            print("Add this line to ~/.bashrc (or ~/.bash_profile):")
            print("  source \"\(path.path)\"")
        default: // zsh
            print("Add these lines to ~/.zshrc, above any existing `compinit` call:")
            print("  fpath=(\"\(path.deletingLastPathComponent().path)\" $fpath)")
            print("  autoload -Uz compinit && compinit")
        }
        print("Then open a new shell.")
    }
}
